name: Deploy Guide to Pages Branch

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Install mdbook
        run: cargo install mdbook --no-default-features --features search --vers "^0.4" --locked

      - name: Build book
        working-directory: ./guide
        run: mdbook build

      - name: Deploy to pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./guide/book
          publish_branch: pages
          force_orphan: true
